modLoader = "javafml"
loaderVersion = "[43,)"
license = "MIT"
issueTrackerURL = "https://github.com/ACGaming/Skewers/issues"
[[mods]]
modId = "skewers"
version = "1.1.1"
displayName = "Skewers"
displayURL = "https://github.com/ACGaming/Skewers"
logoFile = "skewers.png"
credits = "Originally made by Casadis"
authors = "ACGaming"
description = '''
Adds vanilla-friendly skewers you can craft and eat - updated!
'''
[[dependencies.skewers]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.skewers]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,1.20)"
ordering = "NONE"
side = "BOTH"
[[dependencies.skewers]]
modId = "aquaculture"
mandatory = false
versionRange = "[1.19-2.4.0,)"
ordering = "AFTER"
side = "BOTH"
